#page title
page_title                                : ImageFlux - Multiple Exposure Simulator

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
appstore_link                             : https://apps.apple.com/us/app/imageflux-photo-blender/id6740700974  # Enter the correct AppStore link.
playstore_link                            :                                           # Enter Google Play Store URL.
app_icon                                  : assets/logo.png                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter path to icon file manually.
app_name                                  : ImageFlux                                  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
app_price                                 : Free, In-app Subscriptions               # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
app_description                           : "ImageFlux is a powerful multiple exposure simulator that allows photographers to blend and manipulate multiple images in real time, with full support for RAW images and various blend modes."

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_link: "https://WoowApps.info"
email_address: "ozgurodabasi@icloud.com"
instagram_username: "WoowApps"
twitter_username: "WoowApps"

# Feature List
features                                  :

  - title                                 : Multiple Exposure Simulation
    description                           : Blend multiple photos seamlessly with various blend modes, mimicking professional in-camera multiple exposure.
    fontawesome_icon_name                 : magic
    
  - title                                 : RAW Format Support
    description                           : Import and blend RAW images to preserve maximum dynamic range and image details.
    fontawesome_icon_name                 : image

  - title                                 : Real-time Preview
    description                           : Preview your blended images live with instant feedback as you adjust blend modes and layers.
    fontawesome_icon_name                 : play-circle

  - title                                 : High-Resolution Export
    description                           : Export your blended images in full resolution without losing quality. Supports JPG, TIFF, and DNG formats.
    fontawesome_icon_name                 : file-export

  - title                                 : User-friendly Interface
    description                           : A simple and intuitive interface that allows photographers to quickly experiment with and apply multiple exposure effects.
    fontawesome_icon_name                 : user-friends

  - title                                 : Layer Reordering and Deletion
    description                           : Easily reorder layers or remove unwanted images from your blend.
    fontawesome_icon_name                 : layers
  
  - title                                 : Multiple Blend Modes
    description                           : Choose from a variety of blend modes, including Multiply, Screen, Overlay, Soft Light, and more.
    fontawesome_icon_name                 : magic

  - title                                 : Cross-Platform Compatibility
    description                           : Supports all major RAW file types across popular camera brands, allowing seamless integration for photographers.
    fontawesome_icon_name                 : camera

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#222222"
feature_icons_background_color            : "#ffffff"

social_icons_foreground_color             : "#222222"
social_icons_background_color             : "#ffffff"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

