#page title
page_title                                : ImageFlux - Multiple Exposure Simulator

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
appstore_link                             : https://apps.apple.com/tr/app/imageflux-raw-multiexposure/id6740700974  # Enter the correct AppStore link.
# playstore_link                            :                                           # Enter Google Play Store URL.
app_icon                                  : assets/logo.png                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter path to icon file manually.
app_name                                  : ImageFlux                                  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
app_price                                 : Free, In-app Subscriptions               # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
app_description                           : "ImageFlux is a powerful multiple exposure simulator that allows photographers to blend and manipulate multiple images in real time, with full support for RAW images and various blend modes."

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
# your_link: "https://WoowApps.info"
email_address: "info@woowapps.info"
instagram_username: "WoowApps"
bluesky_username: "WoowApps.info"

# Feature List
features                                  :

features:

  - title: Real-Time Layer Control
    description: Pinch, rotate, scale, and reposition layers live with instant feedback on your final composition.
    fontawesome_icon_name: expand-arrows-alt

  - title: Advanced Multiple Exposure Simulation
    description: Simulate analog-style multiple exposure effects with support for layering, stacking, and adjusting blend strength.
    fontawesome_icon_name: magic

  - title: Full RAW Support
    description: Import and work with RAW images for maximum detail and dynamic range. Supports most major camera brands.
    fontawesome_icon_name: image

  - title: Non-Destructive Workflow
    description: Re-edit and tweak your blends at any time. Every layer remains editable, with no quality loss.
    fontawesome_icon_name: undo

  - title: High-Resolution Export
    description: Save your creations in full quality — including JPG, TIFF. Perfect for printing or post-processing.
    fontawesome_icon_name: file-export

  - title: Clean, Minimal Interface
    description: Designed for visual focus. Intuitive and distraction-free, even with complex compositions.
    fontawesome_icon_name: eye

  - title: Flexible Blend Modes
    description: Mix layers using Multiply, Screen, Overlay, Soft Light, and other artist-grade blend modes.
    fontawesome_icon_name: adjust

  - title: Layer Stack Management
    description: Drag to reorder layers or remove any with ease. Includes undo and reset options for fast iteration.
    fontawesome_icon_name: layers

  - title: Optimized for Photographers
    description: Designed with photographers in mind — from street to experimental, analog-style to abstract.
    fontawesome_icon_name: camera-retro


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#222222"
feature_icons_background_color            : "#ffffff"

social_icons_foreground_color             : "#222222"
social_icons_background_color             : "#ffffff"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

